### ISSUE TITLE
[Feature Request] Apply `TrimSpace` on some potentially complicated Alert fields

### ISSUE THREAD

**Issue by stephenchu** [spaceapegames/terraform-provider-wavefront#11]
Terraform's `strings.TrimSpace` will remove whitespace before and after a given string. I would like to propose to use it on the following Wavefront Alert fields that can get big and be implemented in heredocs:

```
condition
displayExpression
additionalInformation
```

Trimming the whitespace will make it consistent with the web values too. For example, with the following _applied_ config:

```
resource "wavefront_alert" "foo" {
  condition = <<-EOS
    ts(stats.gauges.c4-2xl-spot-price) > 0.3
    EOS

  display_expression = <<-EOS
    ts(stats.gauges.c4-2xl-spot-price)
    EOS
```
... when I go to the web UI and just hit "Save" with non change, the `condition` and `display_expression` textboxes show no newline at the end of course, but a subsequent plan shows the following now:
```
  ~ wavefront_alert.foo
      condition:          "ts(stats.gauges.c4-2xl-spot-price) > 0.3" => "ts(stats.gauges.c4-2xl-spot-price) > 0.3\n"
      display_expression: "ts(stats.gauges.c4-2xl-spot-price)" => "ts(stats.gauges.c4-2xl-spot-price)\n"

      <web saved value> => HCL config heredoc value
```

... because the web saved value has no newline, but my heredoc has.

This request is motivated by a [similar code change](https://github.com/hashicorp/terraform/issues/5642) in the Datadog Provider, where their `message` field defines the rendering of an alert.

I haven't started creating other Wavefront objects in this plugin yet, but I am sure some other fields can also benefit from this feature request.

**Comment by stephenchu** [comment]
Sorry, mis-clicked and closed it. I was gonna say, if you welcome contributions I can also do it, although I am not a Golang programmer I am an experienced programmer. All I would need is maybe a `CONTRIBUTION.md` to list the steps to set up the development environment after forking.

**Comment by nathmclean** [comment]
@stephenchu, we're more than happy to have outside contributors, I've added a CONTRIBUTOR file in #13

**Comment by MikeMcMahon** [comment]
https://github.com/spaceapegames/terraform-provider-wavefront/pull/21

as we needed this as well

**Comment by nathmclean** [comment]
Closed by #21

**Comment by stephenchu** [comment]
🙇 ty!

**Comment by ashwin1dd** [comment]
#40 
another fix related to this
