### ISSUE TITLE
parameter_details are being read out of order

### ISSUE THREAD

**Issue by ognnaot** [spaceapegames/terraform-provider-wavefront#22]
With latest release, values_to_readable strings now supports LIST type.  After I apply, it works properly.  Then terraform plan (with no modifications) incorrectly reads back the state and thinks it should apply and make changes.

**Comment by nathmclean** [comment]
Hi @ognnaot, I can't reproduce this issue. I applied the dashboard below and then did another plan and there were no changes to be made. Are you able to provide an example of this issue?

`resource "wavefront_dashboard" "list_param_dash" {
  name = "Terraform Test Dashboard Updated"
  description = "testing, testing"
  url = "tftestcreate"
  section {
    name = "section 1"
    row {
      chart {
        name = "chart 1"
        description = "chart number 1"
        units = "something per unit"
        source {
          name = "source name"
          query = "ts()"
        }
      }
    }
  }
  parameter_details {
    name = "param1"
    label = "param1"
    default_value = "Label"
    hide_from_view = false
    parameter_type = "LIST"
    values_to_readable_strings = {
      b = "c",
      Label = "test",
      c = "d"
      Label2 = "test2",
      a = "b"
    }
  }
  tags = [
    "terraform",
    "test"
  ]
}`

**Comment by ognnaot** [comment]
It worked fine with 1 and 2 parameter_details.  When I got to 3 is when it seems to get mixed up.

    parameter_details {
        name = "param1"
        label = "param1"
        default_value = "Label"
        hide_from_view = false
        parameter_type = "LIST"
        values_to_readable_strings = {
            "b" = "c"
            "Label" = "test"
            "c" = "d"
            "Label2" = "test2"
            "a" = "b"
        }
    }
    parameter_details {
        name = "param2"
        label = "param2"
        default_value = "Label2"
        hide_from_view = false
        parameter_type = "LIST"
        values_to_readable_strings = {
            "b2" = "c2"
            "Label2" = "test2"
            "c2" = "d2"
            "Label2" = "test22"
            "a2" = "b2"
        }
    }
    parameter_details {
        name = "param3"
        label = "param3"
        default_value = "Label3"
        hide_from_view = false
        parameter_type = "LIST"
        values_to_readable_strings = {
            "b3" = "c3"
            "Label3" = "test3"
            "c3" = "d3"
            "Label3" = "test23"
            "a3" = "b3"
        }
    }

**Comment by ognnaot** [comment]
Thanks.  This fix requires parameter_details to be sorted in the terraform declaration.  It was still causing me issues with terraform plan until I changed my declaration order.
