### ISSUE TITLE
escaping wildcards

### ISSUE THREAD

**Issue by calvinx408** [spaceapegames/terraform-provider-wavefront#24]
how are you escaping wildcards? i tried ${urlencode("*")} with no luck.

**Comment by louism517** [comment]
In what context? This isn't a problem we've run into, for instance here is an example of an alert condition with a wildcard:

```
condition = "last(1w, mcount(10m, removeSeries(ts(\"aws.elb.healthyhostcount\" and accountId=xxxxxxxx and LoadBalancerName=* and not AvailabilityZone=*), LoadBalancerName=\"*-prod\"))) = 0"
```

**Comment by calvinx408** [comment]
doh. user error! thanks!
