### ISSUE TITLE
Alert tags falsely shows changes on terraform plan

### ISSUE THREAD

**Issue by ognnaot** [spaceapegames/terraform-provider-wavefront#31]
Similar to other issue with multiple parameter details, multiple tags occasionally confuses terraform plan into thinking there are changes.  The order of tags returned do not always match the original order of the terraform configuration.

  ~ module.test.wavefront_alert.Alert
      tags.0: "test.tag0" => "test.tag2"
      tags.1: "test.tag1" => "test.tag0"
      tags.2: "test.tag2" => "test.tag1"

Running terraform plan a few times will sometimes return no changes.
This may also happen with dashboards but I haven't encountered it yet.

**Comment by ognnaot** [comment]
May be an error in my config.  I corrected some mistakes and can't seem to get it to happen again.

**Comment by louism517** [comment]
Hi @ognnaot - you are correct. This is 100% an issue. The re-ordering of tags seems to happen on the backend after a day or so, we are unsure why.

We have some plans to try forcing the order of the tags on the way out and the way in. But given the delayed re-ordering we are finding it difficult to reproduce in tests. I will try contacting Wavefront to see if they have any ideas.

**Comment by ognnaot** [comment]
Glad I'm not crazy...Yes, the issue showed back up today on a terraform plan.

**Comment by nathmclean** [comment]
Fixed by #33 Make Tags a Set, rather than a List. Lists expect the order to be maintained.
