### ISSUE TITLE
Cannot specify more than one alert target

### ISSUE THREAD

**Issue by sh-aestevez** [spaceapegames/terraform-provider-wavefront#35]
When you specify one alert target the provider works fine:
```
resource "wavefront_alert" "test-alert" {
  name = "Test Alert"
  target = "webhook:k45j38gnk3l48in4"
  condition = "ts(heapster.pod_container.restart_count) > 20"
  display_expression = "ts(heapster.pod_container.restart_count) > 20"
  minutes = 10
  resolve_after_minutes = 5
  severity = "SEVERE"
  tags = [
    "sample"
  ]
}
```

But if try to specify more than one you get following error:

`  target = ["webhook:k45j38gn48in4","webhook:k4nhl3t834n34"]`
`Error: wavefront_alert.test-alert: target must be a single value, not a list`
`Error: wavefront_alert.test-alert target must be a single value, not a map`

This should be supported since it can be done via wavefront.com

**Comment by sh-aestevez** [comment]
According to the API documentation:

```
notificants (Array[string], optional): A derived field listing the webhook ids used by this alert 
```

This might be the missing parameter that has to be specified.

**Comment by nathmclean** [comment]
Target on the API takes a string, you can have multiple targets by providing a comma separated list.
So for your example to work it should be:
`target = ["webhook:k45j38gn48in4,webhook:k4nhl3t834n34"]`

**Comment by sh-aestevez** [comment]
Great thanks!
