### ISSUE TITLE
Add HTML format support for Email Alert Targets

### ISSUE THREAD

**Issue by sanoojm** [spaceapegames/terraform-provider-wavefront#38]
isHtmlContent is an option in Email Alert Targets to add HTML boilerplate to the Email content. This option is by default disabled.

**Comment by sanoojm** [comment]
https://github.com/spaceapegames/terraform-provider-wavefront/pull/39

**Comment by sanoojm** [comment]
This includes a change in --> https://github.com/spaceapegames/go-wavefront

**Comment by sanoojm** [comment]
@louism517 @nathmclean Please review the changes.

**Comment by nathmclean** [comment]
@sanoojm Thanks for the PR, merged and released under `v1.2.0`
