### ISSUE TITLE
Support for multi-threshold alerts

### ISSUE THREAD

**Issue by ashwin1dd** [spaceapegames/terraform-provider-wavefront#42]
Currently the provider only supports `type=CLASSIC` alerts.
This issue is about adding support for `type=THRESHOLD` alerts, which allow us to set different thresholds for different levels of severity in a single alert instance.
https://docs.wavefront.com/alerts.html#creating-a-multi-threshold-alert

Will likely need changes to https://github.com/spaceapegames/go-wavefront as well to enable this.

**Comment by louism517** [comment]
@ashwin1dd Agreed, we should support this. We'll schedule some time to implement.
