### ISSUE TITLE
Alert `resolveAfterMinutes` is not required in API

### ISSUE THREAD

**Issue by stephenchu** [spaceapegames/terraform-provider-wavefront#9]
... but it is marked [as required](https://github.com/spaceapegames/terraform-provider-wavefront/blob/ab7d7a71369f67844a32b42e416cbc95d16d6a19/wavefront/resource_alert.go#L47) in Terraform.

Using this JSON body, I managed to successfully create an alert in their "Try it out!" [button](https://metrics.wavefront.com/api-docs/ui/#!/Alert/createAlert) without it:

```
{
  "name": "Alert Name",
  "target": "user@example.com",
  "condition": "ts(~sample.cpu.loadavg.1m) > 1",
  "displayExpression": "ts(~sample.cpu.loadavg.1m)",
  "minutes": 5,
  "severity": "INFO"
}
```

**Comment by nathmclean** [comment]
Hey,

I've raised a ticket internally to fix this (DEVOPS-2727). It should be planned into a sprint fairly soon. It may require a change to [go-wavefront](https://github.com/spaceapegames/go-wavefront). Thanks for pointing it out.

**Comment by stephenchu** [comment]
@nathmclean Just realized that `displayExpression` is not required either. Would you like me to create a new issue?

Sample payload:

```
{
  "name": "Alert Name",
  "target": "user@example.com",
  "condition": "ts(~sample.cpu.loadavg.1m) > 1",
  "minutes": 5,
  "severity": "INFO",
  "additionalInformation": "Additional Info"
}
```

**Comment by nathmclean** [comment]
@stephenchu I'll include this under the current ticket.

**Comment by nathmclean** [comment]
This [PR in go-wavefront](https://github.com/spaceapegames/go-wavefront/pull/7) lays the groundwork for fixing this bug

**Comment by nathmclean** [comment]
#12 PR raised
